---
# file: tasks/setup-common-RedHat.yml

- name: Install common packages
  become: True
  block:
    - name: EPEL | Install EPEL repository
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Update all existing packages to latest version
      yum:
        name: "*"
        state: latest
      when: bootstrap_yum_update_all
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Install common packages for RedHat
      yum:
        name: '{{ bootstrap_redhat_common_packages }}'
        state: present
        update_cache: "{{ bootstrap_yum_update_cache }}"
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present
        update_cache: "{{ bootstrap_yum_update_cache }}"
      when: bootstrap_install_development_tools
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Setting Timezone
      timezone:
        name: "{{ bootstrap_timezone_name }}"
      tags: [ timezone ]

    - name: Configurating crond for ntpdate
      cron:
        name: "ntpdate"
        minute: "*/5"
        job: "/usr/sbin/ntpdate {{ bootstrap_ntpdate_servers }}"
      tags: [ timezone ]

    - name: Enable and restart crond service
      service:
        name: crond
        enabled: True
        state: restarted
      tags: [ timezone ]

...
