---
# file: tasks/setup-common-RedHat.yml

- name: Install common packages
  become: True
  block:
    - name: EPEL | Install EPEL repository
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Ensure that SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: Update all existing packages to latest version
      yum:
        name: "*"
        state: latest
      when: bootstrap_yum_update_all
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Install common packages for RedHat
      yum:
        name: '{{ bootstrap_redhat_common_packages }}'
        state: present
        update_cache: "{{ bootstrap_yum_update_cache }}"
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Install the Docker packages
      yum:
        name: '{{ bootstrap_redhat_docker_packages }}'
        state: present
        update_cache: "{{ bootstrap_yum_update_cache }}"
      when: bootstrap_install_docker
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Determine Virtualization type
      shell: /usr/bin/hostnamectl | grep -i Virtualization | awk '{ print $2 }'
      args:
          executable: /usr/bin/bash
      register: bootstrap_running_in_vm
      no_log: True

    - name: Install open-vm-tools if we are running inside VMware VM
      yum:
        name: 'open-vm-tools'
        state: latest
        update_cache: "{{ bootstrap_yum_update_cache }}"
      when: bootstrap_running_in_vm.stdout == "vmware"
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

...
